export const nameSynonyms = {
  aaron: ["erin", "ronnie", "ron"],
  erin: ["aron", "ronnie", "ron"],
  ronnie: ["veronica", "vonnie", "ron", "ronna", "ronie", "frony", "franky"],
  ron: ["veronica", "vonnie", "ronna", "ronie", "frony", "franky", "ronnie"],
  abbigail: ["nabby", "abby", "gail", "abbi", "abbey"],
  nabby: ["abigail", "abby", "gail"],
  abby: ["abigail", "nabby", "gail"],
  gail: ["abigail", "nabby", "abby"],
  abbi: ["abbigail", "nabby", "abby", "gail", "abbey"],
  abbey: ["abbigail", "nabby", "abby", "gail", "abbi"],
  abednego: ["bedney"],
  bedney: ["abednego"],
  abel: ["ebbie", "ab", "abe", "eb"],
  ebbie: ["ebenezer", "eben", "eb"],
  ab: ["absalom", "app", "abbie"],
  abe: ["abram", "ab"],
  eb: ["ebenezer", "ebbie", "eben"],
  abiel: ["ab"],
  abigail: ["nabby", "abby", "gail"],
  abijah: ["ab", "bige"],
  bige: ["abijah", "ab"],
  abner: ["ab"],
  abraham: ["ab", "abe"],
  abram: ["ab", "abe"],
  absalom: ["app", "ab", "abbie"],
  app: ["absalom", "ab", "abbie"],
  abbie: ["absalom", "app", "ab"],
  ada: ["andriane", "adri", "rienne"],
  addy: ["adelphia", "philly", "delphia", "adele", "dell"],
  adaline: ["delia", "lena", "dell", "addy", "ada"],
  delia: ["fidelia"],
  lena: ["magdelina", "magda", "madge"],
  dell: ["delores", "lolly", "lola", "della", "dee"],
  addison: ["addie", "addy"],
  addie: ["adrienne", "rienne", "enne"],
  adela: ["della", "delilah", "adelaide", "dell"],
  della: ["rhodella"],
  adelaide: ["della", "adela", "delilah", "dell"],
  heidi: ["adelaide", "adele", "dell", "addy", "della"],
  adele: ["adelphia", "philly", "delphia", "dell", "addy"],
  adelbert: ["del", "albert", "delbert", "bert"],
  del: ["delphine", "delphi", "delf"],
  albert: ["elbert"],
  delbert: ["bert", "del"],
  bert: ["wilber", "will"],
  adeline: ["aline"],
  adelphia: ["philly", "delphia", "adele", "dell", "addy"],
  philly: ["delphia"],
  delphia: ["philly"],
  adolphus: ["dolph", "ado", "adolph"],
  dolph: ["rudolphus", "rudy", "olph", "rolf"],
  ado: ["adolphus", "dolph", "adolph"],
  adolph: ["adolphus", "dolph", "ado"],
  adrian: ["rian"],
  rian: ["adrian"],
  adriane: ["riane"],
  riane: ["adriane"],
  adrienne: ["addie", "rienne", "enne"],
  rienne: ["andriane", "ada", "adri"],
  enne: ["adrienne", "addie", "rienne"],
  agatha: ["aggy"],
  aggy: ["augustina", "tina", "gatsy", "gussie"],
  agnes: ["inez"],
  inez: ["agnes"],
  nessa: ["vanessa", "essa", "vanna"],
  aileen: [
    "helena",
    "eileen",
    "lena",
    "nell",
    "nellie",
    "eleanor",
    "elaine",
    "ellen",
  ],
  allie: ["almena", "mena"],
  alan: ["al"],
  al: ["alyssa", "lissia", "ally"],
  alanson: ["al", "lanson"],
  lanson: ["alanson", "al"],
  alastair: ["al"],
  alazama: ["ali"],
  ali: ["allison", "allie"],
  alberta: ["bert", "allie", "bertie"],
  bertie: ["roberta", "robbie", "bert", "bobbie", "birdie"],
  aldo: ["al"],
  aldrich: ["riche", "rich"],
  riche: ["aldrich", "rich"],
  rich: ["ricky", "dick"],
  aleksandr: ["alex", "alek"],
  alex: ["alexandra", "sandy", "alla", "sandra"],
  alek: ["aleksandr", "alex"],
  aleva: ["levy", "leve"],
  levy: ["aleva", "leve"],
  leve: ["aleva", "levy"],
  alexander: ["alexandria", "drina", "alla", "sandra"],
  sandy: ["sanford"],
  alec: ["alexander", "alex", "al", "sandy"],
  alexandra: ["alex", "sandy", "alla", "sandra"],
  alla: ["alexandria", "drina", "alexander", "sandra"],
  sandra: ["sandy"],
  alexandria: ["drina", "alexander", "alla", "sandra"],
  drina: ["alexandria", "alexander", "alla", "sandra"],
  alexis: ["lexi"],
  lexi: ["alexis"],
  alfonse: ["al"],
  alfred: ["freddy", "al", "fred"],
  freddy: ["winnifred", "freddie", "winny", "winnie", "fred"],
  fred: ["winnifred", "freddie", "freddy", "winny", "winnie"],
  alfreda: ["freddy", "alfy", "freda", "frieda"],
  alfy: ["alfreda", "freddy", "freda", "frieda"],
  freda: ["fredericka", "freddy", "ricka", "frieda"],
  frieda: ["freddie", "freddy", "fred"],
  algernon: ["algy"],
  algy: ["algernon"],
  alice: ["lisa", "elsie", "allie"],
  lisa: ["melissa", "mel", "missy", "milly", "lissa"],
  elsie: ["elsey"],
  alicia: ["lisa", "elsie", "allie"],
  aline: ["adeline"],
  alison: ["ali", "allie"],
  alixandra: ["alix"],
  alix: ["alixandra"],
  allan: ["al"],
  allen: ["al"],
  allisandra: ["allie"],
  allison: ["ali", "allie"],
  allyson: ["ally", "allie"],
  ally: ["alyssa", "lissia", "al"],
  allyssa: ["ally", "allie"],
  almena: ["mena", "allie"],
  mena: ["armena", "arry"],
  almina: ["minnie"],
  minnie: ["wilhelmina", "mina", "wilma", "willie"],
  almira: ["myra"],
  myra: ["samyra"],
  alonzo: ["lon", "al", "lonzo"],
  lon: ["lonzo"],
  lonzo: ["lon"],
  alphinias: ["alphus"],
  alphus: ["alphinias"],
  althea: ["ally"],
  alverta: ["virdie", "vert"],
  virdie: ["alverta", "vert"],
  vert: ["alverta", "virdie"],
  alyssa: ["lissia", "al", "ally"],
  lissia: ["alyssa", "al", "ally"],
  alzada: ["zada"],
  zada: ["alzada"],
  amanda: ["mandy"],
  mandy: ["miranda", "randy", "mira"],
  manda: ["mandy"],
  ambrose: ["brose"],
  brose: ["ambrose"],
  amelia: ["parmelia", "milly", "melia"],
  amy: ["amelia", "mel", "millie", "emily"],
  mel: ["melvin"],
  millie: ["emily", "emmy", "emma", "mel"],
  emily: ["emmy", "millie", "emma", "mel"],
  amos: ["moses", "mose", "moss"],
  moses: ["amos", "mose", "moss"],
  anastasia: ["ana", "stacy"],
  ana: ["anastasia", "stacy"],
  stacy: ["eustacia", "stacia"],
  anderson: ["andy"],
  andy: ["andrew", "drew"],
  andre: ["drea"],
  drea: ["andrea", "rea", "andrew"],
  andrea: ["drea", "rea", "andrew"],
  rea: ["andrea", "drea", "andrew"],
  andrew: ["andy", "drew"],
  drew: ["woodrow", "woody", "wood"],
  andriane: ["ada", "adri", "rienne"],
  adri: ["andriane", "ada", "rienne"],
  angela: ["angel", "angie"],
  angel: ["angelina", "angie", "lina"],
  angie: ["angelina", "angel", "lina"],
  angelica: ["angie", "angel"],
  angelina: ["angel", "angie", "lina"],
  lina: ["paulina", "polly"],
  ann: ["roxanne", "roxie", "rose"],
  annie: ["stephanie", "stephie", "steph"],
  nan: ["nancy", "ann", "nanny"],
  anna: ["savannah", "vannie"],
  anne: ["annie", "ann", "nan"],
  annette: ["anna", "nettie"],
  nettie: ["pernetta"],
  anselm: ["selma"],
  ansel: ["anselm", "selma", "anse", "ance"],
  selma: ["anselm"],
  anse: ["anselm", "ansel", "selma", "ance"],
  ance: ["anselm", "ansel", "selma", "anse"],
  anthony: ["tony"],
  ant: ["antonio", "tony"],
  tony: ["anthony"],
  antoinette: ["tony", "netta", "ann"],
  netta: ["antonia", "tony", "ann"],
  antonia: ["tony", "netta", "ann"],
  antonio: ["ant", "tony"],
  appoline: ["appy", "appie"],
  appy: ["appoline", "appie"],
  appie: ["appoline", "appy"],
  aquilla: ["quil", "quillie"],
  quil: ["aquilla", "quillie"],
  quillie: ["aquilla", "quil"],
  ara: ["arabelle", "bella", "arry", "belle"],
  belle: ["rosabella", "roz", "rosa", "rose"],
  arry: ["armena", "mena"],
  arabella: ["bella", "belle", "isabella"],
  bella: ["isabelle", "tibbie", "nib", "belle", "nibby", "ib", "issy"],
  arabelle: ["ara", "bella", "arry", "belle"],
  araminta: ["armida", "middie", "ruminta", "minty"],
  armida: ["araminta", "middie", "ruminta", "minty"],
  middie: ["araminta", "armida", "ruminta", "minty"],
  ruminta: ["araminta", "armida", "middie", "minty"],
  minty: ["araminta", "armida", "middie", "ruminta"],
  archibald: ["archie"],
  archie: ["archibald"],
  archilles: ["kill", "killis"],
  kill: ["archilles", "killis"],
  killis: ["archilles", "kill"],
  ariadne: ["arie", "ari"],
  arie: ["arielle"],
  ari: ["ariadne", "arie"],
  arielle: ["arie"],
  aristotle: ["telly"],
  telly: ["aristotle"],
  arizona: ["onie", "ona"],
  onie: ["yeona", "ona"],
  ona: ["yeona", "onie"],
  arlene: ["arly", "lena"],
  arly: ["arlene", "lena"],
  armanda: ["mandy"],
  armena: ["mena", "arry"],
  armilda: ["milly"],
  milly: ["permelia", "melly", "mellie"],
  arminda: ["mindie"],
  mindie: ["arminda"],
  arminta: ["minite", "minnie"],
  minite: ["arminta", "minnie"],
  arnold: ["arnie"],
  arnie: ["arnold"],
  aron: ["erin", "ronnie", "ron"],
  artelepsa: ["epsey"],
  epsey: ["artelepsa"],
  artemus: ["art"],
  art: ["arthur"],
  arthur: ["art"],
  arthusa: ["thursa"],
  thursa: ["theresa", "tessie", "thirza", "tessa", "terry", "tracy", "tess"],
  arzada: ["zaddi"],
  zaddi: ["arzada"],
  asahel: ["asa"],
  asa: ["asaph"],
  asaph: ["asa"],
  asenath: ["sene", "assene", "natty"],
  sene: ["asenath", "assene", "natty"],
  assene: ["asenath", "sene", "natty"],
  natty: ["nathaniel", "than", "nathan", "nate", "nat"],
  ashley: ["ash", "leah", "lee"],
  ash: ["ashley", "leah", "lee"],
  leah: ["ashley", "ash", "lee"],
  lee: ["shirley", "sherry", "shirl"],
  aubrey: ["bree"],
  bree: ["breeanna"],
  audrey: ["dee"],
  dee: ["delores", "lolly", "lola", "della", "dell"],
  august: ["augustus", "gus", "austin"],
  gus: ["gustavus", "gussie"],
  augusta: ["tina", "aggy", "gatsy", "gussie"],
  tina: ["christina"],
  gatsy: ["augustina", "tina", "aggy", "gussie"],
  gussie: ["gustavus", "gus"],
  augustina: ["tina", "aggy", "gatsy", "gussie"],
  augustine: ["gus", "austin", "august"],
  austin: ["augustus", "gus", "august"],
  augustus: ["gus", "austin", "august"],
  aurelia: ["ree", "rilly", "orilla", "aurilla", "ora"],
  ree: ["cory", "coco", "cordy"],
  rilly: ["orilla", "ora"],
  orilla: ["rilly", "ora"],
  aurilla: ["aurelia", "ree", "rilly", "orilla", "ora"],
  ora: ["orilla", "rilly"],
  avarilla: ["rilla"],
  rilla: ["serilla"],
  azariah: ["riah", "aze"],
  riah: ["uriah"],
  aze: ["azariah", "riah"],
  bab: ["barbara", "barby", "babs", "bobbie"],
  barby: ["barbara", "babs", "bab", "bobbie"],
  babs: ["barbara", "barby", "bab", "bobbie"],
  barbara: ["barbie"],
  bobbie: ["roberta", "robbie", "bert", "birdie", "bertie"],
  barbery: ["barbara"],
  barbie: ["barbara"],
  barnabas: ["barney"],
  barney: ["bernard", "bernie", "berney"],
  bart: ["barticus"],
  bartholomew: ["bartel", "bat", "meus", "bart", "mees"],
  bartel: ["bartholomew", "bat", "meus", "bart", "mees"],
  bat: ["bartholomew", "bartel", "meus", "bart", "mees"],
  meus: ["bartholomew", "bartel", "bat", "bart", "mees"],
  mees: ["bartholomew", "bartel", "bat", "meus", "bart"],
  barticus: ["bart"],
  bazaleel: ["basil"],
  basil: ["bazaleel"],
  bea: ["blanche"],
  beatrice: ["bea", "trisha", "trixie", "trix"],
  trisha: ["trish", "patricia"],
  trixie: ["trix"],
  trix: ["trixie"],
  becca: ["rebecca", "beck", "reba", "becky"],
  beck: ["rebecca", "becca", "reba", "becky"],
  becky: ["rebecca", "beck", "becca", "reba"],
  bedelia: ["delia", "bridgit"],
  bridgit: ["bedelia", "delia"],
  belinda: ["belle", "linda"],
  linda: ["rosalyn", "roz", "rosa", "rose"],
  isabella: ["tibbie", "nib", "belle", "bella", "nibby", "ib", "issy"],
  benedict: ["bennie", "ben"],
  bennie: ["benjamin", "benjy", "jamie", "ben", "benny"],
  ben: ["benjamin", "benjy", "jamie", "bennie", "benny"],
  benjamin: ["benjy"],
  benjy: ["benjamin"],
  jamie: ["james"],
  benny: ["benjamin", "benjy", "jamie", "bennie", "ben"],
  bernard: ["barney", "bernie", "berney"],
  bernie: ["berney"],
  berney: ["bernie"],
  bob: ["robert", "hob", "hobkin", "dob", "rob", "bobby", "dobbin"],
  bobby: ["roger", "roge", "hodge", "rod", "robby", "rupert", "robin"],
  bertha: ["bert", "birdie", "bertie"],
  birdie: ["roberta", "robbie", "bert", "bobbie", "bertie"],
  bertram: ["bert"],
  bess: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "betsy",
    "liza",
    "betty",
    "bessie",
    "beth",
    "liz",
  ],
  bessie: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "betsy",
    "liza",
    "betty",
    "bess",
    "beth",
    "liz",
  ],
  beth: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "betsy",
    "liza",
    "betty",
    "bessie",
    "bess",
    "liz",
  ],
  betsy: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "liza",
    "betty",
    "bessie",
    "bess",
    "beth",
    "liz",
  ],
  betty: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "betsy",
    "liza",
    "bessie",
    "bess",
    "beth",
    "liz",
  ],
  elizabeth: [
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "betsy",
    "liza",
    "betty",
    "bessie",
    "bess",
    "beth",
    "liz",
  ],
  bethena: ["beth", "thaney"],
  thaney: ["bethena", "beth"],
  beverly: ["bev"],
  bev: ["beverly"],
  bezaleel: ["zeely"],
  zeely: ["bezaleel"],
  biddie: ["obedience", "obed", "beda", "beedy"],
  biddy: ["bridget", "bridie", "bridgie", "biddie"],
  bill: ["willis", "willy"],
  william: ["wilma", "billiewilhelm"],
  billy: ["william", "willy", "bell", "bela", "bill", "will", "willie", "wil"],
  robert: ["hob", "hobkin", "dob", "rob", "bobby", "dobbin", "bob"],
  willie: ["wilson", "will", "willy"],
  blanche: ["bea"],
  rob: ["robert", "hob", "hobkin", "dob", "bobby", "dobbin", "bob"],
  boetius: ["bo"],
  bo: ["boetius"],
  brad: ["bradley"],
  bradford: ["ford", "brad"],
  ford: ["clifford", "cliff"],
  bradley: ["brad"],
  brady: ["broderick", "ricky", "brody", "rick"],
  brody: ["broderick", "ricky", "brady", "rick"],
  breanna: ["bree", "bri"],
  bri: ["brianna"],
  breeanna: ["bree"],
  brenda: ["brandy"],
  brandy: ["brenda"],
  brian: ["bryan", "bryant"],
  bryan: ["brian", "bryant"],
  bryant: ["brian", "bryan"],
  brianna: ["bri"],
  bridget: ["bridie", "biddy", "bridgie", "biddie"],
  bridie: ["bridget", "biddy", "bridgie", "biddie"],
  bridgie: ["bridget", "bridie", "biddy", "biddie"],
  brittany: ["britt"],
  britt: ["brittney"],
  brittney: ["britt"],
  broderick: ["ricky", "brody", "brady", "rick"],
  ricky: ["dick", "rich"],
  rick: ["ricky"],
  caitlin: ["cait", "caity"],
  cait: ["caitlyn", "caity"],
  caity: ["caitlyn", "cait"],
  caitlyn: ["cait", "caity"],
  caldonia: ["calliedona"],
  calliedona: ["caldonia"],
  caleb: ["cal"],
  cal: ["calvin", "vin", "vinny"],
  california: ["callie"],
  callie: ["california"],
  calista: ["kissy"],
  kissy: ["calista"],
  calpurnia: ["cally"],
  cally: ["calpurnia"],
  calvin: ["vin", "vinny", "cal"],
  vin: ["vinson", "vinny", "vinnie"],
  vinny: ["vinson", "vinnie", "vin"],
  cameron: ["ron", "cam", "ronny"],
  cam: ["campbell"],
  ronny: ["ronald"],
  camille: ["millie", "cammie"],
  cammie: ["carmon", "charm", "carm"],
  campbell: ["cam"],
  candace: ["candy", "dacey"],
  candy: ["candace", "dacey"],
  dacey: ["candace", "candy"],
  carlotta: ["lottie"],
  lottie: ["lotta"],
  carlton: ["carl"],
  carl: ["charles", "charlie", "chuck", "chick"],
  carmellia: ["mellia"],
  mellia: ["mellony"],
  carmelo: ["melo"],
  melo: ["carmelo"],
  carmon: ["charm", "cammie", "carm"],
  charm: ["carmon", "cammie", "carm"],
  carm: ["carmon", "charm", "cammie"],
  carol: ["caroline", "lynn", "carrie", "cassie", "carole"],
  lynn: ["philinda", "linda", "lindy"],
  carrie: ["karonhappuck", "karon", "karen", "happy"],
  carolann: ["carol", "carole"],
  cassie: [
    "kathleen",
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kit",
    "trina",
    "cathy",
    "kay",
  ],
  caroline: ["chick", "charlotte", "chuck"],
  carole: ["caroline", "lynn", "carol", "carrie", "cassie"],
  carolyn: ["lynn", "carrie", "cassie"],
  carthaette: ["etta", "etty"],
  etta: ["loretta", "lorrie", "retta"],
  etty: ["henrietta", "hank", "etta", "retta", "nettie"],
  casey: [
    "cathleen",
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kit",
    "trina",
    "cathy",
    "kay",
    "cassie",
  ],
  "k.c.": ["kasey"],
  casper: ["jasper", "jap"],
  jasper: ["jap", "casper"],
  cassandra: ["sandra", "sandy"],
  cassidy: ["cassie", "cass"],
  cass: ["caswell"],
  caswell: ["cass"],
  catherine: ["katarina", "tina"],
  kathy: ["katy", "katie"],
  katy: ["kathy", "katie"],
  kittie: ["kit"],
  kit: ["kittie"],
  trina: [
    "kathleen",
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kit",
    "cathy",
    "kay",
    "cassie",
  ],
  cathy: [
    "kathleen",
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kit",
    "trina",
    "kay",
    "cassie",
  ],
  kay: ["kendra", "kenj", "kenji", "kenny"],
  cathleen: ["cathy", "kathy", "catherine"],
  cecilia: ["sheila"],
  cissy: ["priscilla", "prissy", "cilla"],
  celia: ["celeste", "lessie"],
  cedric: ["ced", "rick", "ricky"],
  ced: ["cedric", "rick", "ricky"],
  celeste: ["lessie", "celia"],
  lessie: ["celeste", "celia"],
  celinda: ["linda", "lynn", "lindy"],
  lindy: ["philinda", "linda", "lynn"],
  charity: ["chat"],
  chat: ["charity"],
  charles: ["charlie", "chuck"],
  charlie: ["charles", "chuck"],
  chuck: ["chick", "charlotte", "caroline"],
  chick: ["charlotte", "caroline", "chuck"],
  charlotte: ["chick", "caroline", "chuck"],
  char: ["charlotte", "sherry", "lottie", "lotta"],
  sherry: ["shirley", "lee", "shirl"],
  lotta: ["lottie"],
  chauncey: ["chan"],
  chan: ["chauncey"],
  cheryl: ["cher"],
  cher: ["cheryl"],
  chesley: ["chet"],
  chet: ["chester"],
  chester: ["chet"],
  chloe: ["clo"],
  clo: ["chloe"],
  chris: ["kristy"],
  christina: ["tina"],
  christopher: ["chris", "kit"],
  christine: ["kris", "kristy", "chrissy", "tina", "chris", "crissy"],
  christa: ["chris"],
  christian: ["chris", "kit"],
  christiana: ["kris", "kristy", "ann", "tina", "christy", "chris", "crissy"],
  kris: ["kristopher", "chris"],
  kristy: ["chris"],
  christy: ["kristine", "kris", "kristy", "tina", "chris", "crissy"],
  crissy: ["kristine", "kris", "kristy", "tina", "christy", "chris"],
  christiano: ["chris"],
  chrissy: ["christine", "kris", "kristy", "tina", "chris", "crissy"],
  christoph: ["chris"],
  cicely: ["cilla"],
  cilla: ["priscilla", "prissy", "cissy"],
  cinderella: ["cindy"],
  arilla: ["cinderella", "rella", "cindy", "rilla"],
  rella: ["cinderella", "arilla", "cindy", "rilla"],
  cindy: ["lucinda", "lu", "lucy", "lou"],
  claire: ["clair", "clare", "clara"],
  clair: ["clarence", "clare"],
  clare: ["clarence", "clair"],
  clara: ["clarissa", "cissy"],
  clarissa: ["cissy", "clara"],
  clarence: ["clare", "clair"],
  clarinda: ["clara"],
  claudia: ["claud"],
  claud: ["claudia"],
  cleatus: ["cleat"],
  cleat: ["cleatus"],
  clement: ["clementine", "clem"],
  clem: ["clementine", "clement"],
  clementine: ["clement", "clem"],
  cliff: ["clifton", "tony"],
  clifford: ["ford", "cliff"],
  clifton: ["tony", "cliff"],
  cole: ["nicole", "nole", "nikki"],
  colie: ["cole"],
  columbus: ["clum"],
  clum: ["columbus"],
  con: ["cornelius", "conny", "niel", "corny"],
  conny: ["cornelius", "niel", "corny", "con"],
  conrad: ["conny", "con"],
  constance: ["connie"],
  connie: ["constance"],
  cordelia: ["delia", "fidelia", "delius"],
  cordy: ["cory", "coco", "ree"],
  corey: ["coco", "cordy", "ree"],
  coco: ["cory", "cordy", "ree"],
  corinne: ["cora", "ora"],
  cora: ["corinne", "ora"],
  cornelia: ["nelly", "cornie", "nelia", "corny", "nelle"],
  nelly: ["nelle"],
  cornie: ["cornelia", "nelly", "nelia", "corny", "nelle"],
  nelia: ["cornelia", "nelly", "cornie", "corny", "nelle"],
  corny: ["cornelius", "conny", "niel", "con"],
  nelle: ["nelly"],
  cornelius: ["conny", "niel", "corny", "con"],
  niel: ["cornelius", "conny", "corny", "con"],
  cory: ["coco", "cordy", "ree"],
  courtney: ["curt", "court"],
  curt: ["curtis"],
  court: ["courtney", "curt"],
  crystal: ["chris", "tal", "stal", "crys"],
  tal: ["crystal", "chris", "stal", "crys"],
  stal: ["crystal", "chris", "tal", "crys"],
  crys: ["crystal", "chris", "tal", "stal"],
  curtis: ["curt"],
  cynthia: ["cintha", "cindy"],
  cintha: ["cynthia", "cindy"],
  cyrenius: ["swene", "cy", "serene", "renius", "cene"],
  swene: ["cyrenius", "cy", "serene", "renius", "cene"],
  cy: ["onicyphorous", "cyphorus", "osaforus", "syphorous", "one", "osaforum"],
  serene: ["cyrenius", "swene", "cy", "renius", "cene"],
  renius: ["cyrenius", "swene", "cy", "serene", "cene"],
  cene: ["cyrenius", "swene", "cy", "serene", "renius"],
  cyrus: ["cy"],
  dahl: ["dalton", "dal"],
  dal: ["dalton", "dahl"],
  dalton: ["dahl", "dal"],
  daniel: ["danny"],
  dan: ["sheridan", "danny", "sher"],
  danny: ["sheridan", "dan", "sher"],
  dann: ["daniel", "dan", "danny"],
  danielle: ["ellie", "dani"],
  ellie: ["helene", "lena", "ella", "ellen"],
  dani: ["danielle", "ellie"],
  daphne: ["daph", "daphie"],
  daph: ["daphne", "daphie"],
  daphie: ["daphne", "daph"],
  darlene: ["lena", "darry"],
  darry: ["darlene", "lena"],
  david: ["dave", "day", "davey"],
  dave: ["david", "day", "davey"],
  day: ["david", "dave", "davey"],
  davey: ["david", "dave", "day"],
  deanne: ["ann", "dee"],
  debbie: ["debra", "deb"],
  deb: ["debra", "debbie"],
  debra: ["deb", "debbie"],
  deborah: ["deb", "debbie", "debby"],
  debby: ["deborah", "deb", "debbie"],
  debora: ["deb", "debbie", "debby"],
  deidre: ["deedee"],
  deedee: ["nadine", "nada"],
  fidelia: ["delia"],
  delius: ["delia", "fidelia", "cordelia"],
  delilah: ["della", "adela", "adelaide", "dell"],
  lil: ["lilly", "lily"],
  lila: ["delilah", "lil", "dell", "della"],
  deliverance: ["delly", "dilly", "della"],
  delly: ["deliverance", "dilly", "della"],
  dilly: ["deliverance", "delly", "della"],
  delores: ["lolly", "lola", "della", "dee", "dell"],
  lolly: ["lillian", "lil", "lilly"],
  lola: ["delores", "lolly", "della", "dee", "dell"],
  delpha: ["philadelphia"],
  philadelphia: ["delphia"],
  delphine: ["delphi", "del", "delf"],
  delphi: ["delphine", "del", "delf"],
  delf: ["delphine", "delphi", "del"],
  demaris: ["dea", "maris", "mary"],
  dea: ["demerias", "maris", "mary"],
  maris: ["demerias", "dea", "mary"],
  mary: ["mitzi", "mittie", "mitty"],
  demerias: ["dea", "maris", "mary"],
  democrates: ["mock"],
  mock: ["democrates"],
  dennis: ["denny"],
  denny: ["dennison"],
  dennison: ["denny"],
  derrick: ["ricky", "eric", "rick"],
  eric: ["rick", "ricky"],
  deuteronomy: ["duty"],
  duty: ["deuteronomy"],
  diana: ["dicey", "didi", "di"],
  dicey: ["eurydice"],
  didi: ["diane", "dicey", "di"],
  di: ["diane", "dicey", "didi"],
  diane: ["dicey", "didi", "di"],
  dicie: ["dicey"],
  dick: ["ricky", "rich"],
  richard: [
    "dick",
    "dickon",
    "dickie",
    "dicky",
    "rick",
    "rich",
    "ricky",
    "richie",
  ],
  dickson: ["dick"],
  domenic: ["dom"],
  dom: ["dominick"],
  dominic: ["dom"],
  dominick: ["dom"],
  donald: ["dony", "donnie", "don", "donny"],
  dony: ["donovan", "donnie", "don", "donny"],
  donnie: ["donovan", "dony", "don", "donny"],
  don: ["donovan", "dony", "donnie", "donny"],
  donny: ["donovan", "dony", "donnie", "don"],
  donovan: ["dony", "donnie", "don", "donny"],
  dorcus: ["darkey"],
  darkey: ["dorcus"],
  dorinda: ["dorothea", "dora"],
  dorothea: ["doda", "dora"],
  dora: ["theodora"],
  doris: ["dora"],
  doda: ["dorothea", "dora"],
  dorothy: ["dortha", "dolly", "dot", "dotty"],
  dortha: ["dorothy", "dolly", "dot", "dotty"],
  dolly: ["dorothy", "dortha", "dot", "dotty"],
  dot: ["dotty"],
  dotty: ["dot"],
  dotha: ["dotty"],
  douglas: ["doug"],
  doug: ["douglas"],
  drusilla: ["silla"],
  silla: ["sarilla"],
  duncan: ["dunk"],
  dunk: ["duncan"],
  earnest: ["ernestine", "ernie"],
  ernestine: ["teeny", "ernest", "tina", "erna"],
  ernie: ["ernest"],
  ebenezer: ["ebbie", "eben", "eb"],
  eben: ["ebenezer", "ebbie", "eb"],
  eddie: ["edwin", "ed", "win", "eddy", "ned"],
  ed: ["edwin", "eddie", "win", "eddy", "ned"],
  eddy: ["edwin", "ed", "eddie", "win", "ned"],
  edgar: ["ed", "eddie", "eddy"],
  edith: ["edie", "edye"],
  edie: ["edythe", "edye"],
  edye: ["edythe", "edie"],
  edmond: ["ed", "eddie", "eddy"],
  edmund: ["ed", "eddie", "ted", "eddy", "ned"],
  ted: ["theodore", "theo", "teddy"],
  ned: ["edwin", "ed", "eddie", "win", "eddy"],
  edna: ["edny"],
  edny: ["edna"],
  eduardo: ["ed", "eddie", "eddy"],
  edward: ["teddy", "ed", "ned", "ted", "eddy", "eddie"],
  teddy: ["theodore", "theo", "ted"],
  edwin: ["edwina"],
  win: ["winfield", "field", "winny"],
  edwina: ["edwin"],
  edyth: ["edie", "edye"],
  edythe: ["edie", "edye"],
  egbert: ["bert", "burt"],
  burt: ["egbert", "bert"],
  eighta: ["athy"],
  athy: ["eighta"],
  eileen: [
    "helena",
    "lena",
    "nell",
    "nellie",
    "eleanor",
    "elaine",
    "ellen",
    "aileen",
  ],
  helen: ["lena", "ella", "ellen", "ellie"],
  elaine: [
    "helena",
    "eileen",
    "lena",
    "nell",
    "nellie",
    "eleanor",
    "ellen",
    "aileen",
  ],
  lainie: ["elaine", "helen"],
  elbert: ["elbertson", "bert"],
  elbertson: ["elbert", "bert"],
  eleanor: [
    "helena",
    "eileen",
    "lena",
    "nell",
    "nellie",
    "elaine",
    "ellen",
    "aileen",
  ],
  lanna: ["eleanor", "nora", "nelly", "ellie", "elaine", "ellen", "lenora"],
  nora: ["nonie"],
  ellen: ["lena"],
  lenora: ["nora", "lee"],
  eleazer: ["lazar"],
  lazar: ["eleazer"],
  elena: ["helen"],
  elias: ["eli", "lee", "lias"],
  eli: ["elisha", "lish"],
  lias: ["elias", "eli", "lee"],
  elijah: ["lige", "eli"],
  lige: ["elijah", "eli"],
  eliphalel: ["life"],
  life: ["eliphalel"],
  eliphalet: ["left"],
  left: ["eliphalet"],
  elisa: ["lisa"],
  elisha: ["lish", "eli"],
  lish: ["elisha", "eli"],
  eliza: ["louise", "lou", "lois"],
  libby: ["lib"],
  lib: ["libby"],
  lizzy: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzie",
    "eliza",
    "betsy",
    "liza",
    "betty",
    "bessie",
    "bess",
    "beth",
    "liz",
  ],
  lizzie: ["liz"],
  liza: [
    "elizabeth",
    "libby",
    "lisa",
    "lib",
    "lizzy",
    "lizzie",
    "eliza",
    "betsy",
    "betty",
    "bessie",
    "bess",
    "beth",
    "liz",
  ],
  liz: ["lizzie"],
  ella: ["luella", "lula", "lu"],
  nellie: ["petronella"],
  nell: ["leonora", "nora", "nellie"],
  ellender: ["nellie", "ellen", "helen"],
  elly: ["elmira", "ellie", "mira"],
  ellswood: ["elsey"],
  elsey: ["elze"],
  elminie: ["minnie"],
  elmira: ["ellie", "elly", "mira"],
  mira: ["miranda", "randy", "mandy"],
  elnora: ["nora"],
  eloise: ["heloise", "lois", "elouise"],
  heloise: ["lois", "eloise", "elouise"],
  louise: ["eliza", "lou", "lois"],
  elouise: ["heloise", "lois", "eloise"],
  elswood: ["elsey"],
  elvira: ["elvie"],
  elvie: ["elvira"],
  elwood: ["woody"],
  woody: ["woodrow", "wood", "drew"],
  elysia: ["lisa"],
  elze: ["elsey"],
  emanuel: ["manuel", "manny"],
  manuel: ["emanuel", "manny"],
  manny: ["manuel", "emanuel"],
  emeline: ["em", "emmy", "emma", "milly", "emily"],
  em: ["emeline", "emmy", "emma", "milly", "emily"],
  emmy: ["emma"],
  emma: ["emmy"],
  emil: ["emily"],
  epaphroditius: ["dite", "ditus", "eppa", "dyche", "dyce"],
  dite: ["epaphroditius", "ditus", "eppa", "dyche", "dyce"],
  ditus: ["epaphroditius", "dite", "eppa", "dyche", "dyce"],
  eppa: ["epaphroditius", "dite", "ditus", "dyche", "dyce"],
  dyche: ["epaphroditius", "dite", "ditus", "eppa", "dyce"],
  dyce: ["epaphroditius", "dite", "ditus", "eppa", "dyche"],
  ephraim: ["eph"],
  eph: ["ephraim"],
  erasmus: ["raze", "rasmus"],
  raze: ["erasmus", "rasmus"],
  rasmus: ["erasmus", "raze"],
  ernest: ["ernestine", "teeny", "tina", "erna"],
  teeny: ["parthenia", "parsuny", "pasoonie", "phenie"],
  erna: ["ernestine", "teeny", "ernest", "tina"],
  erwin: ["irwin"],
  irwin: ["erwin"],
  eseneth: ["senie"],
  senie: ["eseneth"],
  essy: ["estelle", "stella"],
  es: ["essy"],
  estella: ["essy", "stella"],
  stella: ["estelle", "essy"],
  estelle: ["essy", "stella"],
  esther: ["hester", "hessy", "hetty"],
  hester: ["hessy", "esther", "hetty"],
  essie: ["esther", "hester"],
  eudicy: ["dicey"],
  eudora: ["dora"],
  eudoris: ["dossie", "dosie"],
  dossie: ["eudoris", "dosie"],
  dosie: ["eudoris", "dossie"],
  eugene: ["gene"],
  gene: ["eugene"],
  eunice: ["unice", "nicie"],
  nicie: ["unice", "eunice"],
  euphemia: ["effie", "effy"],
  effie: ["euphemia", "effy"],
  effy: ["euphemia", "effie"],
  eurydice: ["dicey"],
  eustacia: ["stacia", "stacy"],
  stacia: ["eustacia", "stacy"],
  eva: ["evaline", "lena", "eve"],
  eve: ["manerva", "minerva", "nervie", "nerva"],
  evaline: ["eva", "lena", "eve"],
  evangeline: ["ev", "evan", "vangie"],
  ev: ["evelyn", "evelina", "eve"],
  evan: ["evangeline", "ev", "vangie"],
  vangie: ["evangeline", "ev", "evan"],
  evelyn: ["evelina", "ev", "eve"],
  evelina: ["evelyn", "ev", "eve"],
  experience: ["exie"],
  exie: ["experience"],
  ezekiel: ["zeke", "ez"],
  zeke: ["zachery", "zachy", "zach", "zac", "zack", "zak", "zakk"],
  ez: ["ezra"],
  ezideen: ["ez"],
  ezra: ["ez"],
  faith: ["fay"],
  fay: ["faith"],
  felicia: ["fel", "felix", "feli"],
  fel: ["felicia", "felix", "feli"],
  felix: ["felicia", "fel", "feli"],
  feli: ["felicia", "fel", "felix"],
  felicity: ["flick", "tick"],
  flick: ["felicity", "tick"],
  tick: ["felicity", "flick"],
  feltie: ["felty"],
  felty: ["valentine"],
  ferdinand: ["freddie", "freddy", "ferdie", "fred"],
  freddie: ["winnifred", "freddy", "winny", "winnie", "fred"],
  ferdie: ["ferdinando", "nando", "fred"],
  ferdinando: ["nando", "ferdie", "fred"],
  nando: ["ferdinando", "ferdie", "fred"],
  flo: ["florence", "flossy", "flora"],
  florence: ["flossy", "flora", "flo"],
  flora: ["florence", "flossy", "flo"],
  flossy: ["florence", "flora", "flo"],
  floyd: ["lloyd"],
  lloyd: ["floyd"],
  fran: ["franklin", "frank"],
  frannie: ["francine", "franniey", "fran", "francie"],
  frances: [
    "sis",
    "cissy",
    "frankie",
    "franniey",
    "fran",
    "francie",
    "frannie",
    "fanny",
  ],
  sis: [
    "frances",
    "cissy",
    "frankie",
    "franniey",
    "fran",
    "francie",
    "frannie",
    "fanny",
  ],
  frankie: ["frank", "francis"],
  franniey: ["francine", "fran", "frannie", "francie"],
  francie: ["francine", "franniey", "fran", "frannie"],
  fanny: [
    "frances",
    "sis",
    "cissy",
    "frankie",
    "franniey",
    "fran",
    "francie",
    "frannie",
  ],
  francine: ["franniey", "fran", "frannie", "francie"],
  francis: ["frankie", "frank"],
  frank: ["franklind"],
  franklin: ["fran", "frank"],
  franklind: ["frank"],
  frederica: ["frederick", "freddy"],
  frederick: ["freddie", "freddy", "fritz", "fred"],
  fritz: ["frederick", "freddie", "freddy", "fred"],
  fredericka: ["freddy", "ricka", "freda", "frieda"],
  ricka: ["fredericka", "freddy", "freda", "frieda"],
  gabriel: ["gabe", "gabby"],
  gabe: ["gabriel", "gabby"],
  gabby: ["gabrielle", "ella"],
  gabriella: ["ella", "gabby"],
  gabrielle: ["ella", "gabby"],
  garrick: ["garri"],
  garri: ["garrick"],
  genevieve: ["jean", "eve", "jenny"],
  jean: ["jeanette", "jessie", "janet", "nettie"],
  jenny: ["jennifer", "jennie", "jenn", "jen"],
  geoffrey: ["geoff", "jeff"],
  geoff: ["jeffrey", "jeff"],
  jeff: ["jeffrey", "geoff"],
  george: ["georgie"],
  georgie: ["george"],
  georgiana: ["georgia"],
  georgia: ["georgiana"],
  gerald: ["gerry", "jerry"],
  gerry: ["geraldine", "gerrie", "jerry", "dina"],
  jerry: ["jereme", "geraldine"],
  geraldine: ["jerry", "jereme"],
  gerrie: ["geraldine", "gerry", "jerry", "dina"],
  dina: ["geraldine", "gerry", "gerrie", "jerry"],
  gerhardt: ["gay"],
  gay: ["gerhardt"],
  gertie: ["gertrude", "gert", "trudy"],
  gertrude: ["trudy"],
  gert: ["gertrude", "gertie", "trudy"],
  trudy: ["gertrude"],
  gilbert: ["bert", "gil", "wilber"],
  gil: ["gilbert", "bert", "wilber"],
  wilber: ["will", "bert"],
  giovanni: ["gio"],
  gio: ["giovanni"],
  gloria: ["glory"],
  glory: ["gloria"],
  governor: ["govie"],
  govie: ["governor"],
  greenberry: ["green", "berry"],
  green: ["greenberry", "berry"],
  berry: ["littleberry", "little", "l.b."],
  greggory: ["gregg"],
  gregg: ["greggory"],
  gregory: ["greg", "gory"],
  greg: ["gregory", "gory"],
  gory: ["gregory", "greg"],
  gretchen: ["margaret"],
  margaret: ["marge", "margery", "margaretta"],
  griselda: ["grissel"],
  grissel: ["griselda"],
  gum: ["montgomery", "monty"],
  monty: ["lamont"],
  gustavus: ["gus", "gussie"],
  gwen: ["gwendolyn", "wendy"],
  wendy: ["wen"],
  gwendolyn: ["gwen", "wendy"],
  hamilton: ["ham"],
  ham: ["hamilton"],
  hannah: ["susannah", "susie", "sue", "sukey"],
  nanny: ["nancy", "ann", "nan"],
  harold: ["harry", "henry"],
  hal: ["howard", "howie"],
  harry: ["henry", "hank", "hal"],
  harriet: ["hattie"],
  hattie: ["harriet"],
  henry: ["hank", "hal", "harry"],
  haseltine: ["hassie"],
  hassie: ["haseltine"],
  heather: ["hetty"],
  hetty: ["mehitabel", "mitty", "mabel", "hitty"],
  helena: [
    "eileen",
    "lena",
    "nell",
    "nellie",
    "eleanor",
    "elaine",
    "ellen",
    "aileen",
  ],
  helene: ["lena", "ella", "ellen", "ellie"],
  lois: ["louise", "eliza", "lou"],
  henrietta: ["hank", "etta", "etty", "retta", "nettie"],
  hank: ["henry", "hal", "harry"],
  retta: ["loretta", "etta", "lorrie"],
  hephsibah: ["hipsie"],
  hipsie: ["hepsibah"],
  hepsibah: ["hipsie"],
  herbert: ["bert", "herb"],
  herb: ["herbert", "bert"],
  herman: ["harman", "dutch"],
  harman: ["herman", "dutch"],
  dutch: ["herman", "harman"],
  hermione: ["hermie"],
  hermie: ["hermione"],
  hessy: ["hester", "esther", "hetty"],
  hezekiah: ["hy", "hez", "kiah"],
  hy: ["hiram"],
  hez: ["hezekiah", "hy", "kiah"],
  kiah: ["hezekiah", "hy", "hez"],
  hiram: ["hy"],
  honora: ["honey", "nora", "norry", "norah"],
  honey: ["honora", "nora", "norry", "norah"],
  norry: ["honora", "honey", "nora", "norah"],
  norah: ["honora", "honey", "nora", "norry"],
  hopkins: ["hopp", "hop"],
  hopp: ["hopkins", "hop"],
  hop: ["hopkins", "hopp"],
  horace: ["horry"],
  horry: ["horace"],
  hortense: ["harty", "tensey"],
  harty: ["hortense", "tensey"],
  tensey: ["hortense", "harty"],
  hosea: ["hosey", "hosie"],
  hosey: ["hosea", "hosie"],
  hosie: ["hosea", "hosey"],
  howard: ["hal", "howie"],
  howie: ["howard", "hal"],
  hubert: ["bert", "hugh", "hub"],
  hugh: ["jehu", "gee"],
  hub: ["hubert", "bert", "hugh"],
  ian: ["john", "jon", "johnny", "jonny", "jonnie", "jack", "jock"],
  john: [
    "jonathon",
    "johnathan",
    "johnathon",
    "jonathan",
    "jon",
    "jonny",
    "johny",
    "jonnie",
  ],
  ignatius: ["natius", "iggy", "nate", "nace"],
  natius: ["ignatius", "iggy", "nate", "nace"],
  iggy: ["ignatzio", "naz", "nace"],
  nate: ["nathaniel", "than", "nathan", "nat", "natty"],
  nace: ["ignatzio", "naz", "iggy"],
  ignatzio: ["naz", "iggy", "nace"],
  naz: ["ignatzio", "iggy", "nace"],
  immanuel: ["manuel", "emmanuel"],
  emmanuel: ["immanuel", "manuel"],
  india: ["indie", "indy"],
  indie: ["india", "indy"],
  indy: ["india", "indie"],
  iona: ["onnie"],
  onnie: ["iona"],
  irene: ["rena"],
  rena: ["serena"],
  irvin: ["irving"],
  irving: ["irv"],
  irv: ["irving"],
  isaac: ["ike", "zeke"],
  ike: ["isaac", "zeke"],
  isabel: ["tibbie", "bell", "nib", "belle", "bella", "nibby", "ib", "issy"],
  tibbie: ["isabelle", "nib", "belle", "bella", "nibby", "ib", "issy"],
  bell: ["william", "willy", "bela", "bill", "will", "billy", "willie", "wil"],
  nib: ["isabelle", "tibbie", "belle", "bella", "nibby", "ib", "issy"],
  nibby: ["isabelle", "tibbie", "nib", "belle", "bella", "ib", "issy"],
  ib: ["isabelle", "tibbie", "nib", "belle", "bella", "nibby", "issy"],
  issy: ["isadora", "dora"],
  isabelle: ["tibbie", "nib", "belle", "bella", "nibby", "ib", "issy"],
  isadora: ["issy", "dora"],
  isaiah: ["zadie", "zay"],
  zadie: ["isaiah", "zay"],
  zay: ["isaiah", "zadie"],
  isidore: ["izzy"],
  izzy: ["isidore"],
  iva: ["ivy"],
  ivy: ["iva"],
  ivan: ["john"],
  jackson: ["jack"],
  jack: ["john", "jon", "johnny", "jonny", "jonnie", "jock", "ian"],
  jacob: ["jacobus"],
  jaap: ["jacob", "jake", "jay"],
  jake: ["jakob"],
  jay: ["jayme"],
  jacobus: ["jacob"],
  jacqueline: ["jackie", "jack"],
  jackie: ["jacqueline", "jack"],
  jahoda: ["hody", "hodie", "hoda"],
  hody: ["jahoda", "hodie", "hoda"],
  hodie: ["jahoda", "hody", "hoda"],
  hoda: ["jahoda", "hody", "hodie"],
  jakob: ["jake"],
  james: ["jamie"],
  jimmy: ["james", "jim", "jamie", "jimmie", "jem"],
  jim: ["jimmie"],
  jimmie: ["jim"],
  jem: ["james", "jimmy", "jim", "jamie", "jimmie"],
  jane: ["virginia", "jennie", "ginny", "virgy", "ginger"],
  janie: ["jane", "jessie", "jean", "jennie"],
  jessie: ["jane", "jess", "janet"],
  jennie: ["virginia", "jane", "ginny", "virgy", "ginger"],
  janet: ["jessie", "jane", "jess"],
  jan: ["janice"],
  janice: ["jan"],
  jannett: ["nettie"],
  jap: ["jasper", "casper"],
  jayme: ["jay"],
  jeannie: ["jeanne", "jane"],
  jeanette: ["jessie", "jean", "janet", "nettie"],
  jeanne: ["jane", "jeannie"],
  jebadiah: ["jeb"],
  jeb: ["jebadiah"],
  jedediah: ["dyer", "jed", "diah"],
  dyer: ["zedediah", "zed", "diah"],
  jed: ["jedidiah", "dyer", "diah"],
  diah: ["zedediah", "dyer", "zed"],
  jedidiah: ["dyer", "jed", "diah"],
  jefferey: ["jeff"],
  jefferson: ["sonny", "jeff"],
  sonny: ["judson", "jud"],
  jeffery: ["jeff"],
  jeffrey: ["geoff", "jeff"],
  jehiel: ["hiel"],
  hiel: ["jehiel"],
  jehu: ["hugh", "gee"],
  gee: ["jehu", "hugh"],
  jemima: ["mima"],
  mima: ["jemima"],
  jennet: ["jessie", "jenny", "jenn"],
  jenn: ["jennifer", "jennie", "jen", "jenny"],
  jennifer: ["jennie", "jenn", "jen", "jenny"],
  jen: ["jennifer", "jennie", "jenn", "jenny"],
  jeremiah: ["jereme", "jerry"],
  jereme: ["jerry", "geraldine"],
  jeremy: ["jezza", "jez"],
  jezza: ["jeremy", "jez"],
  jez: ["jeremy", "jezza"],
  jerita: ["rita"],
  rita: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "margo",
  ],
  jessica: ["jessie"],
  jess: ["jessie", "jane", "janet"],
  jincy: ["jane"],
  jinsy: ["jane"],
  joan: ["johannah", "hannah", "jody", "nonie"],
  jo: ["josephine", "fina", "jody", "josey", "joey", "josie"],
  nonie: ["nora"],
  joann: ["jo"],
  joanna: ["hannah", "jody", "jo", "joan"],
  jody: ["josephine", "fina", "jo", "josey", "joey", "josie"],
  joanne: ["jo"],
  joe: ["joseph", "jody", "jos", "joey"],
  joey: ["josephine", "fina", "jody", "jo", "josey", "josie"],
  johanna: ["jo"],
  johannah: ["hannah", "jody", "joan", "nonie"],
  johannes: ["jonathan", "john", "johnny"],
  jonathan: [
    "jonathon",
    "johnathan",
    "johnathon",
    "jon",
    "jonny",
    "john",
    "johny",
    "jonnie",
  ],
  johnny: ["jon", "john", "jonny", "jonnie"],
  jon: [
    "jonathon",
    "johnathan",
    "johnathon",
    "jonathan",
    "jonny",
    "john",
    "johny",
    "jonnie",
  ],
  jonny: [
    "jonathon",
    "johnathan",
    "johnathon",
    "jonathan",
    "jon",
    "john",
    "johny",
    "jonnie",
  ],
  jonnie: [
    "jonathon",
    "johnathan",
    "johnathon",
    "jonathan",
    "jon",
    "jonny",
    "john",
    "johny",
  ],
  jock: ["john", "jon", "johnny", "jonny", "jonnie", "jack", "ian"],
  johnathan: [
    "jonathon",
    "johnathon",
    "jonathan",
    "jon",
    "jonny",
    "john",
    "johny",
    "jonnie",
  ],
  johnathon: [
    "jonathon",
    "johnathan",
    "jonathan",
    "jon",
    "jonny",
    "john",
    "johny",
    "jonnie",
  ],
  jonathon: [
    "johnathan",
    "johnathon",
    "jonathan",
    "jon",
    "jonny",
    "john",
    "johny",
    "jonnie",
  ],
  johny: [
    "jonathon",
    "johnathan",
    "johnathon",
    "jonathan",
    "jon",
    "jonny",
    "john",
    "jonnie",
  ],
  nathan: ["nathaniel", "than", "nate", "nat", "natty"],
  joseph: ["jody", "jos", "joe", "joey"],
  jos: ["josiah"],
  josephine: ["pheney"],
  fina: ["josephine", "jody", "jo", "josey", "joey", "josie"],
  josey: ["josophine"],
  josie: ["josephine", "fina", "jody", "jo", "josey", "joey"],
  josetta: ["jettie"],
  jettie: ["josetta"],
  josophine: ["josey"],
  joshua: ["jos", "josh"],
  josh: ["joshua", "jos"],
  josiah: ["jos"],
  joyce: ["joy"],
  joy: ["joyce"],
  juanita: ["nita", "nettie"],
  nita: ["juanita", "nettie"],
  judah: ["juder", "jude"],
  juder: ["judah", "jude"],
  jude: ["judith", "judie", "juda", "judy", "judi"],
  judith: ["judy"],
  judie: ["judith", "juda", "judy", "judi", "jude"],
  juda: ["judith", "judie", "judy", "judi", "jude"],
  judy: ["judith"],
  judi: ["judith", "judie", "juda", "judy", "jude"],
  judson: ["sonny", "jud"],
  jud: ["judson", "sonny"],
  julia: ["julie", "jule"],
  julie: ["julia", "jule"],
  jill: ["julia", "julie"],
  julian: ["jule"],
  jule: ["julie", "julia"],
  julias: ["jule"],
  june: ["junior", "junie", "jr"],
  junius: ["june"],
  junior: ["junie", "june", "jr"],
  junie: ["junior", "june", "jr"],
  jr: ["junior", "junie", "june"],
  justin: ["justus", "justina"],
  justus: ["justin", "justina"],
  justina: ["justin", "justus"],
  kaitlin: ["kait", "kaitie"],
  kait: ["kaitlynn", "kaitie"],
  kaitie: ["kaitlynn", "kait"],
  kaitlyn: ["kait", "kaitie"],
  kaitlynn: ["kait", "kaitie"],
  kameron: ["kam"],
  kam: ["kameron"],
  karonhappuck: ["karon", "karen", "carrie", "happy"],
  karon: ["karonhappuck", "karen", "carrie", "happy"],
  karen: ["karonhappuck", "karon", "carrie", "happy"],
  happy: ["karonhappuck", "karon", "karen", "carrie"],
  kasey: ["k.c."],
  katarina: ["catherine", "tina"],
  kate: [
    "katherine",
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kaye",
    "kit",
    "trina",
    "cathy",
    "kay",
    "cassie",
  ],
  katelin: ["kay", "kate", "kaye"],
  kaye: [
    "katherine",
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kit",
    "trina",
    "cathy",
    "kay",
    "kate",
    "cassie",
  ],
  katelyn: ["kay", "kate", "kaye"],
  katherine: [
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kaye",
    "kit",
    "trina",
    "cathy",
    "kay",
    "kate",
    "cassie",
  ],
  kathleen: [
    "kathy",
    "katy",
    "lena",
    "kittie",
    "kit",
    "trina",
    "cathy",
    "kay",
    "cassie",
  ],
  kathryn: ["kathy", "katie"],
  katie: ["katy", "kathy"],
  kayla: ["makayla"],
  kendall: ["ken", "kenny"],
  ken: ["mckenna", "kenna", "meaka"],
  kenny: ["kent", "ken", "kendrick"],
  kendra: ["kenj", "kenji", "kay", "kenny"],
  kenj: ["kendra", "kenji", "kay", "kenny"],
  kenji: ["kendra", "kenj", "kay", "kenny"],
  kendrick: ["kent", "ken", "kenny"],
  kendrik: ["ken", "kenny"],
  kenneth: ["kenny", "ken"],
  kent: ["ken", "kenny", "kendrick"],
  keziah: ["kizza", "kizzie"],
  kizza: ["keziah", "kizzie"],
  kizzie: ["keziah", "kizza"],
  kim: ["kimberly"],
  kimberly: ["kim"],
  kimberley: ["kim"],
  kingsley: ["king"],
  king: ["kingston"],
  kingston: ["king"],
  kristel: ["kris"],
  kristen: ["chris"],
  kristin: ["chris"],
  kristine: ["kris", "kristy", "tina", "christy", "chris", "crissy"],
  kristopher: ["chris", "kris"],
  lafayette: ["laffie", "fate"],
  laffie: ["lafayette", "fate"],
  fate: ["lafayette", "laffie"],
  lamont: ["monty"],
  laodicia: ["dicy", "cenia"],
  dicy: ["laodicia", "cenia"],
  cenia: ["laodicia", "dicy"],
  larry: ["lawrence", "lorry", "lon", "lonny", "lorne"],
  laurence: ["lorry", "larry", "lon", "lonny", "lorne"],
  lawrence: ["lorry", "larry", "lon", "lonny", "lorne"],
  lauren: ["ren", "laurie"],
  ren: ["lauren", "laurie"],
  laurie: ["lauryn"],
  lorry: ["lawrence", "larry", "lon", "lonny", "lorne"],
  lonny: ["lawrence", "lorry", "larry", "lon", "lorne"],
  lorne: ["lawrence", "lorry", "larry", "lon", "lonny"],
  laurinda: ["laura", "lawrence"],
  laura: ["laurinda", "lawrence"],
  lauryn: ["laurie"],
  laveda: ["veda"],
  veda: ["laveda"],
  laverne: ["vernon", "verna"],
  vernon: ["laverne", "verna"],
  verna: ["laverne", "vernon"],
  lavina: ["vina", "viney", "ina"],
  vina: ["melvina"],
  viney: ["louvinia", "vina", "vonnie", "wyncha"],
  ina: ["lavinia", "vina", "viney"],
  lavinia: ["vina", "viney", "ina"],
  lavonia: ["vina", "vonnie", "wyncha", "viney"],
  vonnie: ["veronica", "ron", "ronna", "ronie", "frony", "franky", "ronnie"],
  wyncha: ["louvinia", "vina", "vonnie", "viney"],
  lavonne: ["von"],
  von: ["levone"],
  leanne: ["lea", "annie"],
  lea: ["leanne", "annie"],
  lecurgus: ["curg"],
  curg: ["lecurgus"],
  lemuel: ["lem"],
  lem: ["lemuel"],
  leo: ["leonard", "lineau", "leon", "len", "lenny"],
  leon: ["napoleon", "nap", "nappy"],
  leonard: ["lineau", "leo", "leon", "len", "lenny"],
  lineau: ["leonard", "leo", "leon", "len", "lenny"],
  len: ["leonard", "lineau", "leo", "leon", "lenny"],
  lenny: ["leonard", "lineau", "leo", "leon", "len"],
  leonidas: ["lee", "leon"],
  leonora: ["nora", "nell", "nellie"],
  leonore: ["nora", "honor", "elenor"],
  honor: ["leonore", "nora", "elenor"],
  elenor: ["leonore", "nora", "honor"],
  leroy: ["roy", "lee", "l.r."],
  roy: ["leroy", "lee", "l.r."],
  "l.r.": ["leroy", "roy", "lee"],
  leslie: ["les"],
  les: ["lester"],
  lester: ["les"],
  letitia: ["tish", "titia", "lettice", "lettie"],
  tish: ["letitia", "titia", "lettice", "lettie"],
  titia: ["letitia", "tish", "lettice", "lettie"],
  lettice: ["letitia", "tish", "titia", "lettie"],
  lettie: ["violetta"],
  levi: ["lee"],
  levicy: ["vicy"],
  vicy: ["levicy"],
  levone: ["von"],
  lidia: ["lyddy"],
  lyddy: ["lydia"],
  lilly: ["lily", "lil"],
  lily: ["lilly", "lil"],
  lillah: ["lil", "lilly", "lily", "lolly"],
  lillian: ["lil", "lilly", "lolly"],
  lincoln: ["link"],
  link: ["lincoln"],
  lionel: ["leon"],
  littleberry: ["little", "berry", "l.b."],
  little: ["littleberry", "berry", "l.b."],
  "l.b.": ["littleberry", "little", "berry"],
  lou: ["lucinda", "lu", "lucy", "cindy"],
  lorenzo: ["loren"],
  loren: ["lorenzo"],
  loretta: ["etta", "lorrie", "retta"],
  lorrie: ["lorraine"],
  lorraine: ["lorrie"],
  louis: ["lewis", "louise", "louie", "lou"],
  lu: ["luella", "lula", "ella"],
  lewis: ["louis", "louise", "louie", "lou"],
  louie: ["louis", "lewis", "louise", "lou"],
  louisa: ["eliza", "lou", "lois"],
  louvinia: ["vina", "vonnie", "wyncha", "viney"],
  lucas: ["luke"],
  luke: ["luther"],
  lucia: ["lucy", "lucius"],
  lucy: ["lucinda"],
  lucius: ["lucia", "lucy"],
  lucias: ["luke"],
  lucille: ["cille", "lu", "lucy", "lou"],
  cille: ["lucille", "lu", "lucy", "lou"],
  lucina: ["sinah"],
  sinah: ["lucina"],
  lucinda: ["lucy"],
  lucretia: ["creasey"],
  creasey: ["lucretia"],
  luella: ["lula", "ella", "lu"],
  lula: ["luella", "ella", "lu"],
  lunetta: ["nettie"],
  lurana: ["lura"],
  lura: ["lurana"],
  luther: ["luke"],
  lydia: ["lyddy"],
  lyndon: ["lindy", "lynn"],
  mabel: ["mehitabel", "hetty", "mitty", "hitty"],
  mehitabel: ["hetty", "mitty", "mabel", "hitty"],
  amabel: ["mabel", "mehitabel"],
  mac: ["malcolm", "mal", "malc"],
  mc: ["mack", "mac"],
  mack: ["mackenzie", "kenzy", "mac"],
  mackenzie: ["kenzy", "mac", "mack"],
  kenzy: ["mackenzie", "mac", "mack"],
  maddison: ["maddie", "maddi"],
  maddie: ["madeline", "maggie", "lena", "magda", "maddy", "madge", "maddi"],
  maddi: ["madeline", "maggie", "lena", "magda", "maddy", "madge", "maddie"],
  maddy: ["madison", "mattie"],
  madelyn: ["madie", "madeline"],
  madeline: ["madie", "madelyn"],
  madge: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  maggie: [
    "margarita",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  magda: ["magdelina", "lena", "madge"],
  madie: ["madeline", "madelyn"],
  madison: ["mattie", "maddy"],
  mattie: ["matthew", "thys", "matt", "thias", "matty"],
  maegen: ["meg"],
  meg: ["meghan"],
  magdalena: ["maggie", "lena"],
  magdelina: ["lena", "magda", "madge"],
  mahala: ["hallie"],
  hallie: ["mahala"],
  makayla: ["kayla"],
  malachi: ["mally"],
  mally: ["malachi"],
  malcolm: ["mac", "mal", "malc"],
  mal: ["malcolm", "mac", "malc"],
  malc: ["malcolm", "mac", "mal"],
  malinda: ["lindy"],
  mandie: ["amanda"],
  manerva: ["minerva", "nervie", "eve", "nerva"],
  minerva: ["minnie"],
  nervie: ["manerva", "minerva", "eve", "nerva"],
  nerva: ["manerva", "minerva", "nervie", "eve"],
  manoah: ["noah"],
  noah: ["manoah"],
  manola: ["nonnie"],
  nonnie: ["manola"],
  marcus: ["mark"],
  mark: ["marcus"],
  peg: ["peggy"],
  midge: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  margy: ["marjorie", "margie"],
  margie: ["marjorie", "margy"],
  peggy: ["peg"],
  maggy: [
    "margaret",
    "maggie",
    "meg",
    "peg",
    "midge",
    "margy",
    "margie",
    "madge",
    "peggy",
    "marge",
    "daisy",
    "margery",
    "gretta",
    "rita",
  ],
  marge: ["margery", "margaret", "margaretta"],
  daisy: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "peggie",
    "rita",
    "margo",
  ],
  margery: ["marge", "margaret", "margaretta"],
  gretta: [
    "margaretta",
    "maggie",
    "meg",
    "peg",
    "midge",
    "margie",
    "madge",
    "peggy",
    "marge",
    "daisy",
    "margery",
    "rita",
  ],
  margaretta: ["marge", "margery", "margaret"],
  margarita: [
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  metta: [
    "margarita",
    "maggie",
    "meg",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  greta: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  megan: ["meg"],
  maisie: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
    "margo",
  ],
  peggie: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "rita",
    "margo",
  ],
  margo: [
    "margarita",
    "maggie",
    "meg",
    "metta",
    "midge",
    "greta",
    "megan",
    "maisie",
    "madge",
    "marge",
    "daisy",
    "peggie",
    "rita",
  ],
  marjorie: ["margy", "margie"],
  marguerite: ["peggy"],
  mariah: [
    "marietta",
    "mercy",
    "polly",
    "may",
    "molly",
    "mitzi",
    "minnie",
    "mollie",
    "mae",
    "maureen",
    "marion",
    "marie",
    "mamie",
    "mary",
    "maria",
  ],
  maria: [
    "marietta",
    "mariah",
    "mercy",
    "polly",
    "may",
    "molly",
    "mitzi",
    "minnie",
    "mollie",
    "mae",
    "maureen",
    "marion",
    "marie",
    "mamie",
    "mary",
  ],
  marian: ["marianna", "marion"],
  marianna: ["marian", "marion"],
  marion: ["mary"],
  marie: [
    "marietta",
    "mariah",
    "mercy",
    "polly",
    "may",
    "molly",
    "mitzi",
    "minnie",
    "mollie",
    "mae",
    "maureen",
    "marion",
    "mamie",
    "mary",
    "maria",
  ],
  mae: ["may"],
  marietta: [
    "mariah",
    "mercy",
    "polly",
    "may",
    "molly",
    "mitzi",
    "minnie",
    "mollie",
    "mae",
    "maureen",
    "marion",
    "marie",
    "mamie",
    "mary",
    "maria",
  ],
  mercy: ["mercedes", "merci", "sadie"],
  polly: ["pauline"],
  may: ["mae"],
  molly: ["mary", "mamie", "mae", "polly", "mitzi"],
  mitzi: ["mary", "mittie", "mitty"],
  mollie: [
    "marietta",
    "mariah",
    "mercy",
    "polly",
    "may",
    "molly",
    "mitzi",
    "minnie",
    "mae",
    "maureen",
    "marion",
    "marie",
    "mamie",
    "mary",
    "maria",
  ],
  maureen: ["mary"],
  mamie: ["mary", "molly", "mae", "polly", "mitzi"],
  marilyn: ["mary"],
  marissa: ["rissa"],
  rissa: ["marissa"],
  marsha: ["marcie", "mary"],
  marcie: ["marsha", "mary"],
  martha: ["marty", "mattie", "mat", "patsy", "patty"],
  marty: ["martin"],
  mat: ["mathew", "maty"],
  patsy: ["patty"],
  patty: ["patricia"],
  martin: ["marty"],
  martina: ["tina"],
  martine: ["tine"],
  tine: ["martine"],
  marv: ["marvin"],
  marvin: ["marv"],
  masayuki: ["masa"],
  masa: ["masayuki"],
  mathew: ["mat", "maty"],
  maty: ["mathew", "mat"],
  mathilda: ["tillie", "patty"],
  tillie: ["tilford"],
  matilda: ["tilly", "maud", "matty"],
  tilly: ["matilda", "maud", "matty"],
  maud: ["middy"],
  matty: ["matthew", "thys", "matt", "thias", "mattie"],
  matthew: ["thys", "matt", "thias", "mattie", "matty"],
  thys: ["matthias", "matt", "thias"],
  matt: ["matthias", "thys", "thias"],
  thias: ["matthias", "thys", "matt"],
  matthias: ["thys", "matt", "thias"],
  middy: ["maud"],
  maurice: ["morey"],
  morey: ["seymour", "see"],
  mavery: ["mave"],
  mave: ["mavine"],
  mavine: ["mave"],
  maximillian: ["max"],
  max: ["maxwell"],
  maxine: ["max"],
  maxwell: ["max"],
  mckenna: ["ken", "kenna", "meaka"],
  kenna: ["mckenna", "ken", "meaka"],
  meaka: ["mckenna", "ken", "kenna"],
  medora: ["dora"],
  meghan: ["meg"],
  mitty: ["mitzie", "mittie"],
  hitty: ["mehitabel", "hetty", "mitty", "mabel"],
  melanie: ["mellie"],
  mellie: ["permelia", "melly", "milly"],
  melchizedek: ["zadock", "dick"],
  zadock: ["melchizedek", "dick"],
  melinda: ["linda", "mel", "lynn", "mindy", "lindy"],
  mindy: ["melinda", "linda", "mel", "lynn", "lindy"],
  melissa: ["missy"],
  missy: ["melissa"],
  lissa: ["melissa", "lisa", "mel", "missy", "milly"],
  mellony: ["mellia"],
  melody: ["lodi"],
  lodi: ["melody"],
  melvin: ["mel"],
  melvina: ["vina"],
  mercedes: ["merci", "sadie", "mercy"],
  merci: ["mercedes", "sadie", "mercy"],
  sadie: ["sarah", "sally"],
  merv: ["mervyn"],
  mervin: ["merv"],
  mervyn: ["merv"],
  micajah: ["cage"],
  cage: ["micajah"],
  michael: ["mike", "micky", "mick"],
  micky: ["mike", "mick", "michael"],
  mike: ["micky", "mick", "michael"],
  micah: ["michael", "micky", "mike", "mick", "mikey"],
  mick: ["mike", "micky", "michael"],
  mikey: ["micheal", "mike", "miky"],
  micheal: ["mike", "miky", "mikey"],
  miky: ["micheal", "mike", "mikey"],
  michelle: ["mickey"],
  mickey: ["michelle"],
  mildred: ["milly"],
  millicent: ["missy", "milly"],
  wilhelmina: ["mina", "wilma", "willie", "minnie"],
  miranda: ["randy", "mandy", "mira"],
  randy: ["randolph", "dolph"],
  miriam: ["mimi", "mitzi", "mitzie"],
  mimi: ["miriam", "mitzi", "mitzie"],
  mitzie: ["mittie", "mitty"],
  mitch: ["mitchell"],
  mitchell: ["mitch"],
  mittie: ["mitzie", "mitty"],
  monet: ["nettie"],
  monica: ["monna", "monnie"],
  monna: ["monica", "monnie"],
  monnie: ["monica", "monna"],
  monteleon: ["monte"],
  monte: ["monteleon"],
  montesque: ["monty"],
  montgomery: ["monty", "gum"],
  morris: ["morey"],
  mortimer: ["mort"],
  mort: ["mortimer"],
  mose: ["moses", "amos", "moss"],
  moss: ["moses", "amos", "mose"],
  muriel: ["mur"],
  mur: ["muriel"],
  myrtle: ["myrt", "myrti", "mert"],
  myrt: ["myrtle", "myrti", "mert"],
  myrti: ["myrtle", "myrt", "mert"],
  mert: ["myrtle", "myrt", "myrti"],
  nadine: ["nada", "deedee"],
  nada: ["nadine", "deedee"],
  nancy: ["ann", "nan", "nanny"],
  naomi: ["omi"],
  omi: ["naomi"],
  napoleon: ["nap", "nappy", "leon"],
  nap: ["napoleon", "nappy", "leon"],
  nappy: ["napoleon", "nap", "leon"],
  natalie: ["natty", "nettie"],
  natasha: ["tasha", "nat"],
  tasha: ["tash", "tashie"],
  nat: ["nathaniel", "than", "nathan", "nate", "natty"],
  nathaniel: ["than", "nathan", "nate", "nat", "natty"],
  than: ["nathaniel", "nathan", "nate", "nat", "natty"],
  nelson: ["nels"],
  nels: ["nelson"],
  newt: ["newton"],
  newton: ["newt"],
  nicholas: ["nick", "claes", "claas", "nic", "nicky", "nico", "nickie"],
  nick: ["nikolas", "claes", "nic", "nicky", "nico", "nickie"],
  claes: ["nikolas", "nick", "nic", "nicky", "nico", "nickie"],
  claas: ["nicholas", "nick", "claes", "nic", "nicky", "nico", "nickie"],
  nic: ["nikolas", "nick", "claes", "nicky", "nico", "nickie"],
  nicky: ["nikolas", "nick", "claes", "nic", "nico", "nickie"],
  nico: ["nikolas", "nick", "claes", "nic", "nicky", "nickie"],
  nickie: ["nikolas", "nick", "claes", "nic", "nicky", "nico"],
  nicodemus: ["nick", "nic", "nicky", "nico", "nickie"],
  nicole: ["nole", "nikki", "cole"],
  nole: ["nicole", "nikki", "cole"],
  nikki: ["nikole"],
  nikolas: ["nick", "claes", "nic", "nicky", "nico", "nickie"],
  nikole: ["nikki"],
  norbert: ["bert", "norby"],
  norby: ["norbert", "bert"],
  norbusamte: ["norbu"],
  norbu: ["norbusamte"],
  nowell: ["noel"],
  noel: ["nowell"],
  obadiah: ["dyer", "obed", "obie", "diah"],
  obed: ["obedience", "beda", "beedy", "biddie"],
  obie: ["obediah"],
  obedience: ["obed", "beda", "beedy", "biddie"],
  beda: ["obedience", "obed", "beedy", "biddie"],
  beedy: ["obedience", "obed", "beda", "biddie"],
  obediah: ["obie"],
  octavia: ["tave", "tavia"],
  tave: ["octavia", "tavia"],
  tavia: ["octavia", "tave"],
  odell: ["odo"],
  odo: ["odell"],
  olive: ["nollie", "livia", "ollie"],
  nollie: ["olivia", "livia", "ollie"],
  livia: ["olivia", "nollie", "ollie"],
  ollie: ["oliver"],
  oliver: ["ollie"],
  olivia: ["nollie", "livia", "ollie"],
  onicyphorous: ["cyphorus", "osaforus", "syphorous", "one", "cy", "osaforum"],
  cyphorus: ["onicyphorous", "osaforus", "syphorous", "one", "cy", "osaforum"],
  osaforus: ["onicyphorous", "cyphorus", "syphorous", "one", "cy", "osaforum"],
  syphorous: ["onicyphorous", "cyphorus", "osaforus", "one", "cy", "osaforum"],
  one: ["onicyphorous", "cyphorus", "osaforus", "syphorous", "cy", "osaforum"],
  osaforum: ["onicyphorous", "cyphorus", "osaforus", "syphorous", "one", "cy"],
  orlando: ["roland", "rollo", "lanny", "rolly"],
  roland: ["rollo", "lanny", "orlando", "rolly"],
  orphelia: ["phelia"],
  phelia: ["orphelia"],
  ossy: ["waldo", "ozzy"],
  ozzy: ["waldo", "ossy"],
  oswald: ["ozzy", "waldo", "ossy"],
  waldo: ["ozzy", "ossy"],
  otis: ["ode", "ote"],
  ode: ["otis", "ote"],
  ote: ["otis", "ode"],
  pamela: ["pam"],
  pam: ["pamela"],
  pandora: ["dora"],
  parmelia: ["amelia", "milly", "melia"],
  melia: ["parmelia", "amelia", "milly"],
  parthenia: ["teeny", "parsuny", "pasoonie", "phenie"],
  parsuny: ["parthenia", "teeny", "pasoonie", "phenie"],
  pasoonie: ["parthenia", "teeny", "parsuny", "phenie"],
  phenie: ["parthenia", "teeny", "parsuny", "pasoonie"],
  patience: ["pat", "patty"],
  pat: ["patrick", "pate", "peter", "patsy", "paddy"],
  patricia: ["trish", "trisha"],
  tricia: ["patricia", "pat", "patsy", "patty", "patti"],
  patti: ["patricia", "tricia", "pat", "patsy", "patty"],
  patrick: ["pate", "peter", "pat", "patsy", "paddy"],
  pate: ["peter", "pete"],
  peter: ["pete", "pate"],
  paddy: ["patrick", "pate", "peter", "pat", "patsy"],
  paul: ["polly"],
  paula: ["polly", "lina"],
  paulina: ["polly", "lina"],
  pauline: ["polly"],
  pelegrine: ["perry"],
  perry: ["peregrine"],
  penelope: ["penny"],
  penny: ["penelope"],
  percival: ["percy"],
  percy: ["percival"],
  peregrine: ["perry"],
  permelia: ["melly", "milly", "mellie"],
  melly: ["permelia", "milly", "mellie"],
  pernetta: ["nettie"],
  persephone: ["seph", "sephy"],
  seph: ["persephone", "sephy"],
  sephy: ["persephone", "seph"],
  pete: ["peter", "pate"],
  petronella: ["nellie"],
  pheney: ["josephine"],
  pheriba: ["pherbia", "ferbie"],
  pherbia: ["pheriba", "ferbie"],
  ferbie: ["pheriba", "pherbia"],
  philander: ["fie"],
  fie: ["philander"],
  philetus: ["leet", "phil"],
  leet: ["philetus", "phil"],
  phil: ["phillip"],
  philinda: ["linda", "lynn", "lindy"],
  philip: ["phil"],
  philipina: ["phoebe", "penie"],
  phoebe: ["fifi"],
  penie: ["philipina", "phoebe"],
  phillip: ["phil"],
  philomena: ["menaalmena"],
  menaalmena: ["philomena"],
  fifi: ["phoebe"],
  pinckney: ["pink"],
  pink: ["pinckney"],
  pleasant: ["ples"],
  ples: ["pleasant"],
  pocahontas: ["pokey"],
  pokey: ["pocahontas"],
  posthuma: ["humey"],
  humey: ["posthuma"],
  prescott: ["scotty", "scott", "pres"],
  scotty: ["scott", "sceeter", "squat", "scottie"],
  scott: ["scotty", "sceeter", "squat", "scottie"],
  pres: ["prescott", "scotty", "scott"],
  priscilla: ["prissy", "cissy", "cilla"],
  prissy: ["priscilla", "cissy", "cilla"],
  providence: ["provy"],
  provy: ["providence"],
  prudence: ["prudy"],
  prue: ["prudence", "prudy"],
  prudy: ["prudence"],
  rachel: ["shelly"],
  shelly: ["shelton", "tony", "shel"],
  rafaela: ["rafa"],
  rafa: ["rafaela"],
  ramona: ["mona"],
  mona: ["ramona"],
  randolph: ["dolph", "randy"],
  raphael: ["ralph"],
  ralph: ["raphael"],
  ray: ["raymond"],
  raymond: ["ray"],
  reba: ["rebecca", "beck", "becca", "becky"],
  rebecca: ["beck", "becca", "reba", "becky"],
  reggie: ["reginald", "naldo", "reg", "renny"],
  reginald: ["reynold"],
  reg: ["reginald", "reggie", "naldo", "renny"],
  regina: ["reggie", "gina"],
  gina: ["regina", "reggie"],
  naldo: ["ronald", "ron", "ronny", "ronnie"],
  renny: ["reginald", "reggie", "naldo", "reg"],
  relief: ["leafa"],
  leafa: ["relief"],
  reuben: ["rube"],
  rube: ["reuben"],
  reynold: ["reginald"],
  rhoda: ["rodie"],
  rodie: ["rhoda"],
  rhodella: ["della"],
  rhyna: ["rhynie"],
  rhynie: ["rhyna"],
  ricardo: ["rick", "ricky"],
  dickon: [
    "richard",
    "dick",
    "dickie",
    "dicky",
    "rick",
    "rich",
    "ricky",
    "richie",
  ],
  dickie: [
    "richard",
    "dick",
    "dickon",
    "dicky",
    "rick",
    "rich",
    "ricky",
    "richie",
  ],
  dicky: [
    "richard",
    "dick",
    "dickon",
    "dickie",
    "rick",
    "rich",
    "ricky",
    "richie",
  ],
  richie: [
    "richard",
    "dick",
    "dickon",
    "dickie",
    "dicky",
    "rick",
    "rich",
    "ricky",
  ],
  hob: ["robert", "hobkin", "dob", "rob", "bobby", "dobbin", "bob"],
  hobkin: ["robert", "hob", "dob", "rob", "bobby", "dobbin", "bob"],
  dob: ["robert", "hob", "hobkin", "rob", "bobby", "dobbin", "bob"],
  dobbin: ["robert", "hob", "hobkin", "dob", "rob", "bobby", "bob"],
  roberta: ["robbie", "bert", "bobbie", "birdie", "bertie"],
  robbie: ["roberta", "bert", "bobbie", "birdie", "bertie"],
  roderick: ["rod", "erick", "rickie", "roddy"],
  rod: ["roger", "roge", "bobby", "hodge", "robby", "rupert", "robin"],
  erick: ["roderick", "rod", "rickie", "roddy"],
  rickie: ["roderick", "rod", "erick", "roddy"],
  roddy: ["roderick", "rod", "erick", "rickie"],
  rodger: ["roge", "bobby", "hodge", "rod", "robby", "rupert", "robin"],
  roge: ["roger", "bobby", "hodge", "rod", "robby", "rupert", "robin"],
  hodge: ["roger", "roge", "bobby", "rod", "robby", "rupert", "robin"],
  robby: ["roger", "roge", "bobby", "hodge", "rod", "rupert", "robin"],
  rupert: ["roger", "roge", "bobby", "hodge", "rod", "robby", "robin"],
  robin: ["roger", "roge", "bobby", "hodge", "rod", "robby", "rupert"],
  rodney: ["rod"],
  roger: ["roge", "bobby", "hodge", "rod", "robby", "rupert", "robin"],
  rollo: ["roland", "lanny", "orlando", "rolly"],
  lanny: ["roland", "rollo", "orlando", "rolly"],
  rolly: ["roland", "rollo", "lanny", "orlando"],
  ronald: ["ronny"],
  rosa: ["rosalyn", "linda", "roz", "rose"],
  rose: ["roxanne", "roxie", "ann"],
  rosabel: ["belle", "roz", "rosa", "rose"],
  roz: ["roseanna", "rose", "ann", "rosie"],
  rosabella: ["belle", "roz", "rosa", "rose"],
  rosalinda: ["linda", "roz", "rosa", "rose"],
  rosalyn: ["linda", "roz", "rosa", "rose"],
  roscoe: ["ross"],
  ross: ["roscoe"],
  rosie: ["roseanna", "rose", "ann", "roz"],
  roseann: ["rose", "ann", "rosie", "roz"],
  roseanna: ["rose", "ann", "rosie", "roz"],
  roseanne: ["ann"],
  rosina: ["sina"],
  sina: ["rosina"],
  roxane: ["rox", "roxie"],
  rox: ["roxane", "roxie"],
  roxie: ["roxanne", "rose", "ann"],
  roxanna: ["roxie", "rose", "ann"],
  roxanne: ["roxie", "rose", "ann"],
  rudolph: ["dolph", "rudy", "olph", "rolf"],
  rudy: ["rudolphus", "dolph", "olph", "rolf"],
  olph: ["rudolphus", "dolph", "rudy", "rolf"],
  rolf: ["rudolphus", "dolph", "rudy", "olph"],
  rudolphus: ["dolph", "rudy", "olph", "rolf"],
  russell: ["russ", "rusty"],
  russ: ["russell", "rusty"],
  rusty: ["russell", "russ"],
  ryan: ["ry"],
  ry: ["ryan"],
  sabrina: ["brina"],
  brina: ["sabrina"],
  safieel: ["safie"],
  safie: ["safieel"],
  salome: ["loomie"],
  loomie: ["salome"],
  salvador: ["sal"],
  sal: ["solomon", "salmon", "sol", "solly", "saul", "zolly"],
  samantha: ["sammy", "sam", "mantha"],
  sammy: ["samuel", "sam"],
  sam: ["samuel", "sammy"],
  mantha: ["samantha", "sammy", "sam"],
  samuel: ["sammy", "sam"],
  sampson: ["sam"],
  samson: ["sam"],
  samyra: ["myra"],
  sanford: ["sandy"],
  sarah: ["sally", "sadie"],
  sally: ["sarah", "sadie"],
  sarilla: ["silla"],
  savannah: ["vannie", "anna"],
  vannie: ["vandalia"],
  sceeter: ["scott", "scotty", "squat", "scottie"],
  squat: ["scott", "scotty", "sceeter", "scottie"],
  scottie: ["scott", "scotty", "sceeter", "squat"],
  sebastian: ["sebby", "seb"],
  sebby: ["sebastian", "seb"],
  seb: ["sebastian", "sebby"],
  serena: ["rena"],
  serilla: ["rilla"],
  seymour: ["see", "morey"],
  see: ["seymour", "morey"],
  shaina: ["sha", "shay"],
  sha: ["sharon", "shay"],
  shay: ["sharon", "sha"],
  sharon: ["sha", "shay"],
  sheila: ["cecilia"],
  sheldon: ["shelly"],
  shelton: ["tony", "shel", "shelly"],
  shel: ["shelton", "tony", "shelly"],
  sheridan: ["dan", "danny", "sher"],
  sher: ["sheryl"],
  sheryl: ["sher"],
  shirley: ["sherry", "lee", "shirl"],
  shirl: ["shirley", "sherry", "lee"],
  sibbilla: ["sybill", "sibbie", "sibbell"],
  sybill: ["sibbie"],
  sibbie: ["sybill"],
  sibbell: ["sibbilla", "sybill", "sibbie"],
  sidney: ["syd", "sid"],
  syd: ["sidney", "sid"],
  sid: ["sydney"],
  sigfired: ["sid"],
  sigfrid: ["sid"],
  sigismund: ["sig"],
  sig: ["sigismund"],
  silas: ["si"],
  si: ["sylvester", "sy", "sly", "vet", "syl", "vester", "vessie"],
  silence: ["liley"],
  liley: ["silence"],
  silvester: ["vester", "si", "sly", "vest", "syl"],
  vester: ["sylvester", "sy", "sly", "vet", "syl", "si", "vessie"],
  sly: ["sylvester", "sy", "vet", "syl", "vester", "si", "vessie"],
  vest: ["silvester", "vester", "si", "sly", "syl"],
  syl: ["sylvester", "sy", "sly", "vet", "vester", "si", "vessie"],
  simeon: ["si", "sion"],
  sion: ["simon", "si"],
  simon: ["si", "sion"],
  smith: ["smitty"],
  smitty: ["smith"],
  socrates: ["crate"],
  crate: ["socrates"],
  solomon: ["sal", "salmon", "sol", "solly", "saul", "zolly"],
  salmon: ["solomon", "sal", "sol", "solly", "saul", "zolly"],
  sol: ["solomon", "sal", "salmon", "solly", "saul", "zolly"],
  solly: ["solomon", "sal", "salmon", "sol", "saul", "zolly"],
  saul: ["solomon", "sal", "salmon", "sol", "solly", "zolly"],
  zolly: ["solomon", "sal", "salmon", "sol", "solly", "saul"],
  sondra: ["dre", "sonnie"],
  dre: ["sondra", "sonnie"],
  sonnie: ["sondra", "dre"],
  sophia: ["sophronia", "frona", "fronia"],
  sophie: ["sophia"],
  sophronia: ["frona", "sophia", "fronia"],
  frona: ["sophronia", "sophia", "fronia"],
  fronia: ["sophronia", "frona", "sophia"],
  stephan: ["steve"],
  steve: ["steven", "steph", "stevie"],
  stephanie: ["stephie", "annie", "steph"],
  stephie: ["stephanie", "annie", "steph"],
  steph: ["steven", "steve", "stevie"],
  stephen: ["steve", "steph"],
  steven: ["steve", "steph", "stevie"],
  stevie: ["steven", "steve", "steph"],
  stuart: ["stu"],
  stu: ["stuart"],
  sue: ["suzanne", "suki", "susie"],
  susie: ["suzanne", "suki", "sue"],
  susan: ["hannah", "susie", "sue", "sukey", "suzie"],
  sullivan: ["sully", "van"],
  sully: ["sullivan", "van"],
  van: ["sullivan", "sully"],
  sukey: ["susannah", "hannah", "susie", "sue"],
  suzie: ["susie"],
  susannah: ["hannah", "susie", "sue", "sukey"],
  suzanne: ["suki", "sue", "susie"],
  suki: ["suzanne", "sue", "susie"],
  sydney: ["sid"],
  sylvanus: ["sly", "syl"],
  sylvester: ["sy", "sly", "vet", "syl", "vester", "si", "vessie"],
  sy: ["sylvester", "sly", "vet", "syl", "vester", "si", "vessie"],
  vet: ["sylvester", "sy", "sly", "syl", "vester", "si", "vessie"],
  vessie: ["sylvester", "sy", "sly", "vet", "syl", "vester", "si"],
  tabby: ["tabitha"],
  tabitha: ["tabby"],
  tamarra: ["tammy"],
  tammy: ["tamarra"],
  tanafra: ["tanny"],
  tanny: ["tanafra"],
  tash: ["tasha", "tashie"],
  tashie: ["tasha", "tash"],
  temperance: ["tempy"],
  tempy: ["temperance"],
  terence: ["terry"],
  terry: ["theresa", "tessie", "thirza", "tessa", "tracy", "tess", "thursa"],
  teresa: ["tessa", "theresa"],
  tess: ["theresa", "tessie", "thirza", "tessa", "terry", "tracy", "thursa"],
  theresa: ["tessie", "thirza", "tessa", "terry", "tracy", "tess", "thursa"],
  tessa: ["theresa", "tessie", "thirza", "terry", "tracy", "tess", "thursa"],
  thad: ["thaddeus"],
  thaddeus: ["thad"],
  theo: ["theodosia", "dosia", "theodosius"],
  theodore: ["theo", "ted", "teddy"],
  theodora: ["dora"],
  theodosia: ["theo", "dosia", "theodosius"],
  dosia: ["theodosia", "theo", "theodosius"],
  theodosius: ["theodosia", "theo", "dosia"],
  theophilus: ["ophi"],
  ophi: ["theophilus"],
  theotha: ["otha"],
  otha: ["theotha"],
  tessie: ["theresa", "thirza", "tessa", "terry", "tracy", "tess", "thursa"],
  thirza: ["theresa", "tessie", "tessa", "terry", "tracy", "tess", "thursa"],
  tracy: ["theresa", "tessie", "thirza", "tessa", "terry", "tess", "thursa"],
  thom: ["thomas", "tommy", "tom"],
  thomas: ["tommy"],
  tommy: ["thomas"],
  tom: ["thomas", "tommy"],
  thomasa: ["tamzine"],
  tamzine: ["thomasa"],
  tiffany: ["tiff", "tiffy"],
  tiff: ["tiffany", "tiffy"],
  tiffy: ["tiffany", "tiff"],
  tilford: ["tillie"],
  tim: ["timothy", "timmy"],
  timothy: ["tim", "timmy"],
  timmy: ["timothy", "tim"],
  tobias: ["bias", "toby"],
  bias: ["tobias", "toby"],
  toby: ["tobias", "bias"],
  tranquilla: ["trannie", "quilla"],
  trannie: ["tranquilla", "quilla"],
  quilla: ["tranquilla", "trannie"],
  trish: ["trisha", "patricia"],
  tryphena: ["phena"],
  phena: ["tryphena"],
  unice: ["eunice", "nicie"],
  uriah: ["riah"],
  ursula: ["sulie", "sula"],
  sulie: ["ursula", "sula"],
  sula: ["ursula", "sulie"],
  valentina: ["felty", "vallie", "val"],
  vallie: ["valentina", "felty", "val"],
  val: ["valeri", "valerie"],
  valentine: ["felty"],
  valeri: ["valerie", "val"],
  valerie: ["valeri", "val"],
  vanburen: ["buren"],
  buren: ["vanburen"],
  vandalia: ["vannie"],
  vanessa: ["essa", "vanna", "nessa"],
  essa: ["vanessa", "vanna", "nessa"],
  vanna: ["vanessa", "essa", "nessa"],
  vernisee: ["nicey"],
  nicey: ["vernisee"],
  veronica: ["vonnie", "ron", "ronna", "ronie", "frony", "franky", "ronnie"],
  ronna: ["veronica", "vonnie", "ron", "ronie", "frony", "franky", "ronnie"],
  ronie: ["veronica", "vonnie", "ron", "ronna", "frony", "franky", "ronnie"],
  frony: ["veronica", "vonnie", "ron", "ronna", "ronie", "franky", "ronnie"],
  franky: ["veronica", "vonnie", "ron", "ronna", "ronie", "frony", "ronnie"],
  vic: ["vincenzo", "vinnie", "vin", "vinny", "vince"],
  vicki: ["victoria", "torie", "vic", "tory", "vicky"],
  vickie: ["vicki", "vicky", "victoria"],
  vicky: ["victoria", "torie", "vic", "vicki", "tory"],
  victor: ["vic", "vicki", "vickie", "vicky"],
  victoria: ["torie", "vic", "vicki", "tory", "vicky"],
  torie: ["victoria", "vic", "vicki", "tory", "vicky"],
  tory: ["victoria", "torie", "vic", "vicki", "vicky"],
  vijay: ["vij"],
  vij: ["vijay"],
  vincent: ["vic", "vince", "vinnie", "vin", "vinny"],
  vince: ["vincenzo", "vic", "vinnie", "vin", "vinny"],
  vinnie: ["vinson", "vinny", "vin"],
  vincenzo: ["vic", "vinnie", "vin", "vinny", "vince"],
  vinson: ["vinny", "vinnie", "vin"],
  viola: ["ola", "vi"],
  ola: ["viola", "vi"],
  vi: ["vivian", "viv"],
  violetta: ["lettie"],
  virginia: ["jane", "jennie", "ginny", "virgy", "ginger"],
  ginny: ["virginia", "jane", "jennie", "virgy", "ginger"],
  virgy: ["virginia", "jane", "jennie", "ginny", "ginger"],
  ginger: ["virginia", "jane", "jennie", "ginny", "virgy"],
  vivian: ["vi", "viv"],
  viv: ["vivian", "vi"],
  wallace: ["wally"],
  wally: ["walter", "walt"],
  walt: ["walter", "wally"],
  walter: ["wally", "walt"],
  washington: ["wash"],
  wash: ["washington"],
  webster: ["webb"],
  webb: ["webster"],
  wen: ["wendy"],
  wesley: ["wes"],
  wes: ["westley", "west", "farmboy"],
  westley: ["west", "wes", "farmboy"],
  west: ["westley", "wes", "farmboy"],
  farmboy: ["westley", "west", "wes"],
  will: ["wilson", "willy", "willie"],
  wilbur: ["will", "bill", "willie", "fred"],
  willy: ["wilson", "will", "willie"],
  wilda: ["willie"],
  wilfred: ["will", "willie", "fred", "wil"],
  wil: ["william", "willy", "bell", "bela", "bill", "will", "billy", "willie"],
  wilhelm: ["wil", "willie"],
  mina: ["wilhelmina", "wilma", "willie", "minnie"],
  wilma: ["william", "billiewilhelm"],
  bela: ["william", "willy", "bell", "bill", "will", "billy", "willie", "wil"],
  willis: ["willy", "bill"],
  billiewilhelm: ["wilma", "william"],
  wilson: ["will", "willy", "willie"],
  winfield: ["field", "winny", "win"],
  field: ["winfield", "winny", "win"],
  winny: ["winnifred"],
  winifred: ["freddie", "winnie", "winnet"],
  winnie: ["winnifred", "freddie", "freddy", "winny", "fred"],
  winnet: ["winifred", "freddie", "winnie"],
  winnifred: ["winny"],
  winton: ["wint"],
  wint: ["winton"],
  woodrow: ["woody", "wood", "drew"],
  wood: ["woodrow", "woody", "drew"],
  yeona: ["onie", "ona"],
  yoshihiko: ["yoshi"],
  yoshi: ["yoshihiko"],
  yulan: ["lan", "yul"],
  lan: ["yulan", "yul"],
  yul: ["yulan", "lan"],
  yvonne: ["vonna"],
  vonna: ["yvonne"],
  zach: ["zack", "zak"],
  zack: ["zach", "zak"],
  zak: ["zack", "zach"],
  zachariah: ["zachy", "zach", "zeke", "zac", "zack", "zak", "zakk"],
  zachy: ["zachery", "zach", "zeke", "zac", "zack", "zak", "zakk"],
  zac: ["zachery", "zachy", "zach", "zeke", "zack", "zak", "zakk"],
  zakk: ["zachery", "zachy", "zach", "zeke", "zac", "zack", "zak"],
  zachary: ["zachy", "zach", "zeke", "zac", "zack", "zak", "zakk"],
  zachery: ["zachy", "zach", "zeke", "zac", "zack", "zak", "zakk"],
  zebedee: ["zeb"],
  zeb: ["zebedee"],
  zedediah: ["dyer", "zed", "diah"],
  zed: ["zedediah", "dyer", "diah"],
  zephaniah: ["zeph"],
  zeph: ["zephaniah"],
};
