name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: build
        run: |
          npm run build
          npm run format
          npm run lint
          npm run typecheck

      - name: test
        run: npm run test
